[package]
name = "cb58"
version = "0.0.2"
edition = "2021"
license = "Apache-2.0"
homepage = "https://lyquor.xyz/"
description = "Implementation of CB58 standard used by Avalanche."

[dependencies]
bs58 = "0.5.1"
sha2 = "0.10.8"
